version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-22.9
  jobs:
    pre_build:
      - python -m pip install -e python_packages/jupyter_lsp/ --no-deps --no-build-isolation
      - jlpm

sphinx:
  builder: html
  configuration: docs/conf.py

conda:
  environment: docs/rtd.yml

formats:
  - htmlzip
  - epub
