#!/usr/bin/env bash
set -eux
python -m pip install -e . --ignore-installed --no-deps -vv
jupyter serverextension enable --sys-prefix --py jupyter_lsp
jlpm bootstrap
jupyter labextension install . @krassowski/jupyterlab_go_to_definition
