#!/usr/bin/env bash
set -eux
# do a dev install of the server side
python -m pip install -e . --ignore-installed --no-deps -vv
jupyter serverextension enable --sys-prefix --py jupyter_lsp

# should have no extensions
jupyter labextension list

# do a dev build of the client side
jlpm bootstrap

# link all pieces to lab (no build)
jlpm lab:link && jupyter labextension list

# TODO: should this move into the monorepo?
# link third party extensions
jupyter labextension install @krassowski/jupyterlab_go_to_definition --no-build

# actually build
jupyter lab build && jupyter labextension list
