parameters:
  platforms:
    - name: Linux
      vmImage: ubuntu-16.04
      activate: source activate base
    - name: MacOSX
      vmImage: macos-10.14
      activate: source activate base
    - name: Windows
      vmImage: vs2017-win2016
      activate: call activate base
  pythons:
    - name: ThreeSix
      spec: '=3.6'
      lab: '>=2,<3.0.0a0'
      nodejs: '>=10,<11.0.0.a0'
    - name: ThreeSeven
      spec: '=3.7'
      lab: '>=2,<3.0.0a0'
      nodejs: '>=12,<13.0.0a0'
    - name: ThreeEight
      spec: '=3.8'
      lab: '>=2,<3.0.0a0'
      nodejs: '>=13,<14.0.0a0'
  js_cov_packages:
    - jupyterlab-go-to-definition
    - jupyterlab-lsp
  env_update: conda env update -n base --file env-test.yml --quiet
  lab_link: jupyter labextension link --debug --no-build $(LINKED_EXTENSIONS)
  lab_ext: jupyter labextension install --debug --no-build $(FIRST_PARTY_LABEXTENSIONS)
  lab_build: jupyter lab build --debug --dev-build=False --minimize=True

jobs:
  - ${{ each platform in parameters.platforms }}:
      - ${{ each python in parameters.pythons}}:
          - job: ${{ platform.name }}${{ python.name }}
            pool:
              vmImage: ${{ platform.vmImage }}
            steps:
              - template: steps.conda.yml
                parameters:
                  name: ${{ platform.name }}
                  packages: "'python${{ python.spec }}'"

              - script: ${{ platform.activate }} && cd ci && python env_template.py "${{ python.spec }}" "${{ python.lab }}" "${{ python.nodejs }}"
                displayName: generate env with python, lab, and nodejs version

              - script: ${{ parameters.env_update }} || ${{ parameters.env_update }} || ${{ parameters.env_update }}
                displayName: update conda environment with test dependencies

              - script: conda info && conda list -n base
                displayName: list conda packages and info

              - script: ${{ platform.activate }} && jlpm || jlpm || jlpm
                displayName: install npm dependencies

              - script: ${{ platform.activate }} && jlpm build
                displayName: build typescript

              - script: ${{ platform.activate }} && python setup.py sdist bdist_wheel
                displayName: build python distributions

              - script: ${{ platform.activate }} && jlpm lerna run bundle
                displayName: build npm bundles

              - script: ${{ platform.activate }} && cd dist && python -m pip install jupyter_lsp-$(PY_JLSP_VERSION)-py3-none-any.whl --no-deps
                displayName: install python wheel

              - script: ${{ platform.activate }} && python scripts/jedi_cache.py
                displayName: warm up jedi cache

              - script: ${{ platform.activate }} && jlpm test
                displayName: run frontend unit tests

              - task: PublishTestResults@2
                displayName: publish frontend test results
                inputs:
                  testResultsFiles: packages/**/junit.xml
                  testRunTitle: 'Jest ${{ platform.name }}${{ python.name }}'
                  mergeTestResults: true
                condition: always()

              - ${{ each js_package in parameters.js_cov_packages }}:
                  - task: PublishCodeCoverageResults@1
                    displayName: 'publish ${{ js_package }} coverage'
                    inputs:
                      codeCoverageTool: Cobertura
                      summaryFileLocation: 'packages/${{ js_package }}/coverage/cobertura-coverage.xml'
                    condition: always()

              - script: ${{ platform.activate }} && jupyter serverextension list
                displayName: list server extensions

              - script: ${{ platform.activate }} && python scripts/utest.py --test-run-title="Pytest ${{ platform.name }}${{ python.name }}"
                displayName: run python tests

              - script: ${{ platform.activate }} && ${{ parameters.lab_link }} || ${{ parameters.lab_link }} || ${{ parameters.lab_link }}
                displayName: install support packages

              - script: ${{ platform.activate }} && ${{ parameters.lab_ext }} || ${{ parameters.lab_ext }} || ${{ parameters.lab_ext }}
                displayName: install labextensions

              - script: ${{ platform.activate }} && jupyter labextension list
                displayName: list labextensions before build

              - script: ${{ platform.activate }} && ${{ parameters.lab_build }} || ${{ parameters.lab_build }} || ${{ parameters.lab_build }}
                displayName: build lab

              - script: ${{ platform.activate }} && jupyter labextension list
                displayName: list labextensions after build

              - script: ${{ platform.activate }} && python scripts/atest.py
                displayName: run browser tests

              - task: PublishTestResults@2
                displayName: publish browser test results
                inputs:
                  testResultsFiles: atest/output/*.xunit.xml
                  testRunTitle: 'Robot ${{ platform.name }}${{ python.name }}'
                  mergeTestResults: true
                condition: always()

              - task: PublishPipelineArtifact@0
                displayName: publish browser test output
                inputs:
                  targetPath: atest/output
                  artifactName: $(Agent.JobStatus) Robot ${{ platform.name }}${{ python.name }} $(Build.BuildId)
                condition: always()
