parameters:
  platforms:
    - name: Linux
      vmImage: ubuntu-16.04
      activate: source activate
  pythons:
    - name: ThreeSeven
      spec: '>=3.7,<3.8.0a0'
      lab: '>=2,<3.0.0a0'
      nodejs: '>=12,<13.0.0a0'
  env_update: mamba env update -n jupyterlab-lsp --file env-test.yml --quiet
  env_lint: mamba env update -n jupyterlab-lsp --file requirements/lint.yml --quiet

jobs:
  - ${{ each platform in parameters.platforms }}:
      - ${{ each python in parameters.pythons}}:
          - job: Lint
            pool:
              vmImage: ${{ platform.vmImage }}
            steps:
              - template: steps.mamba.yml
                parameters:
                  name: ${{ platform.name }}

              - script: ${{ platform.activate }} && cd ci && python env_template.py "${{ python.spec }}" "${{ python.lab }}" "${{ python.nodejs }}"
                displayName: generate env with python, lab, and nodejs version

              - script: ${{ parameters.env_update }} || ${{ parameters.env_update }} || ${{ parameters.env_update }}
                displayName: testing dependencies

              - script: ${{ parameters.env_lint }} || ${{ parameters.env_lint }} || ${{ parameters.env_lint }}
                displayName: linting dependencies

              - script: ${{ platform.activate }} jupyterlab-lsp && python scripts/integrity.py
                displayName: check integrity of package versions

              - script: ${{ platform.activate }} jupyterlab-lsp && jlpm || jlpm || jlpm
                displayName: install npm dependencies

              - script: ${{ platform.activate }} jupyterlab-lsp && python scripts/lint.py
                displayName: lint backend

              - script: ${{ platform.activate }} jupyterlab-lsp && jlpm build:schema
                displayName: build schema so linting can complete

              - script: ${{ platform.activate }} jupyterlab-lsp && jlpm lint:check
                displayName: lint frontend
