#!/usr/bin/env bash
set -eux

# Build labextensions
jlpm bootstrap

# Do a dev install of the server side
python -m pip install -e . --ignore-installed --no-deps -vv
jupyter serverextension enable --sys-prefix --py jupyter_lsp

# List extensions
jupyter labextension list
